[package]
name = "koji-retriever"
version = "0.0.1"
edition = "2023"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
curl = { version = "0.4.43" }
assert_cmd = { version = "2.0.8" }
predicates = { version = "2.1.5" }