[package]
name = "koji-retriever"
version = "0.5.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.16" }
clap = { version = "4.5.30", features = ["derive"] }
curl = { version = "0.4.47" }
lazy_static = { version = "1.5.0" }
predicates = { version = "3.1.3" }
