[package]
name = "koji-retriever"
version = "0.3.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.8" }
clap = { version = "3.2.8", features = ["derive"] }
curl = { version = "0.4.43" }
lazy_static = { version = "1.4.0" }
predicates = { version = "2.1.5" }
