[package]
name = "koji-retriever"
version = "0.4.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.12" }
clap = { version = "4.4.12", features = ["derive"] }
curl = { version = "0.4.44" }
lazy_static = { version = "1.4.0" }
predicates = { version = "3.0.4" }
