[package]
name = "koji-retriever"
version = "0.4.0"
edition = "2021"

[dependencies]
assert_cmd = { version = "2.0.14" }
clap = { version = "4.5.4", features = ["derive"] }
curl = { version = "0.4.46" }
lazy_static = { version = "1.4.0" }
predicates = { version = "3.1.0" }
