name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - fedora:latest
          - quay.io/centos/centos:stream9
          - debian:latest
          - ubuntu:latest
        stable: [true]
    steps:
    - uses: actions/checkout@v3
    - name: Build (release)
      run: cargo build --release --verbose
    - name: Run tests (release)
      run: cargo test --release --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose
