---
name: 'Yamllint'
"on":
  push:
    branches:
      - main
    paths-ignore:
      - '**.yml'
  pull_request:
    paths-ignore:
      - '**.yml'
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/workflows/*.yaml'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Yamllint (actions)'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/actions-rs/*.yaml'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Yamllint (root)'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: './.*yaml'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
